version: '3'
services:
  db:
    image: 'postgres:11.2'
    ports:
      - "5432:5432"
    volumes:
      - ./pgData:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: database_development

  app:
    working_dir: /node
    entrypoint: ["sh","entrypoint.sh"]
    image: node:12
    ports:
      - "3000:3000"
    volumes:
      - .:/node
    environment:
      DB_HOST: db
    depends_on:
      - db